# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jackie' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jackie
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'GooglePlacesAPI'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
  target 'JackieTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JackieUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
