source 'https://github.com/CocoaPods/Specs.git'
target 'Jackie' do
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'GooglePlacesAPI'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
end
