source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Jackie' do
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'GoogleMapsDirections', '~> 1.1'
    pod 'AFNetworking', '~> 3.0'
end
